= Guia Ironhack: Inglés

Si me hubieran dicho hace un año, que a día de hoy estaría haciendo un curso en inglés hubiera sido el primero en reirme. Pero en un año pasan muchas cosas, empezando por un viaje a Londres. Ese fue el primer paso, y aunque fueron sólo unos cuantos días, el tener que sacarte las castañas del fuego recurriendo al inglés es un gran paso y uno que tarde o temprano hay que dar.
Cuando vi Ironhack, el hecho de que fuera en otro idioma era algo que me echaba para atrás. Mientras una vocecilla se metía en mi mente: apenas eres capaz de encadenar 3 frases sin que un "eeeeehhhh" interrumpa tu intento de inglés. Y en parte esa vocecilla sigue teniendo parte de razón, pero no pierdes nada por dejarte llevar en tu arrebato de locura.
En las 8 semanas de Ironhack, pasas por 3 etapas:

*Primera etapa: "El guiri español"*

Esta etapa se caracteriza por la incapaz de reconocer ese acento tan raro que tienen tus compañeros más internacionales y buscas comunicarte en castellano con algún miembro hispano del grupo. Esta etapa dura unos días, mientras te adaptas a escuchar inglés en todos sus acentos y variedades en las numerosas historias de tus compañeros. 

*Segunda etapa: "Lengua desatada"*

Tras unos largos primeros días, y tras coger confianza con todo el team Ironhack empiezas a ignorar esa vocecilla que te dice: "quédate callado y no nos dejes quedar mal". Aquí estas más o menos cómodo con el inglés, y si tienes que mantener una conversación ya no tienes ningún problema - y sí, una cerveza puede ayudarte a sentirte con más soltura, pero solo una. En esta etapa sueles recurrir al español para preguntar por alguna palabra en inglés que no sepas y sueles hablarlo tras darte numerosos cabezazos porque las cosas no funcionan.

*Tercera etapa: "Languages exchange"*

Tras un duro entrenamiento de un mes, ya eres capaz de entender todas las conversaciones y te desenvuelves con relativa soltura. En esta etapa las conversaciones suelen estar llenas de intercambios de palabras en diferentes idiomas recurriendo al proceso de: "vale, no me acuerdo de esta palabra" y la conversación continua con la descripción de la palabra o acción, "is when you do ..." esperando a decribir lo suficientemente bien como para que te contesten con esa olvidada palabra que pasa a formar parte de tu diccionario. El hecho más curioso que sucede en esta etapa es la transformación que sufres al hablar con miembros del grupo que hablen español. El idioma que hables con ellos ya no importa, si la conversación comienza en inglés se queda en inglés. Hasta el punto en el que llevar una hora hablando inglés con alguien que sabes que habla español, hasta que alguno dice: "Tío, porque llevamos media hora hablando inglés cuando estamos solo nosotros dos"

En fin, si al principio el inglés formaba parte de una de las cosas que me echaban para atrás, ahora solo puedo mirarlo como un plus añadido a una gran experiencia.
